# Generated by Django 3.0.5 on 2022-09-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='usefulSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('My project', 'My project'), ('Useful site', 'Useful site')], max_length=100)),
                ('work', models.CharField(choices=[('My project', 'My project'), ('Useful site', 'Useful site')], max_length=100)),
                ('url', models.URLField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('client', models.CharField(default='none', max_length=100)),
            ],
        ),
    ]
